# Generated by Django 5.2.1 on 2025-05-18 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/images/', verbose_name='تصویر گزینه'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن گزینه'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('text', 'متنی'), ('image', 'تصویری')], default='text', max_length=10, verbose_name='نوع گزینه'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='تصویر سوال'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن سوال'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'متنی'), ('image', 'تصویری'), ('video', 'ویدیویی')], default='text', max_length=10, verbose_name='نوع سوال'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_video',
            field=models.FileField(blank=True, null=True, upload_to='questions/videos/', verbose_name='ویدیو سوال'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='گزینه صحیح'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
