# Generated by Django 5.2.1 on 2025-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retake',
            field=models.BooleanField(default=True, verbose_name='امکان شرکت مجدد'),
        ),
    ]
