# Generated by Django 5.2.1 on 2025-05-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='username_or_phone',
            new_name='username_phone',
        ),
    ]
